packages:
  - apps/*
  - packages/*

# Build settings
verifyDepsBeforeRun: install
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
ignoredBuiltDependencies:
  - sharp

# Other Settings
shellEmulator: true
