packages:
  - apps/*
  - packages/*

# Build settings (https://pnpm.io/settings#build-settings)
verifyDepsBeforeRun: install
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
ignoredBuiltDependencies:
  - sharp

# Other Settings (https://pnpm.io/settings#other-settings)
shellEmulator: true
