packages:
  - apps/*
  - packages/*

# Build settings (https://pnpm.io/settings#build-settings)
verifyDepsBeforeRun: install
strictDepBuilds: true
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

# Other Settings (https://pnpm.io/settings#other-settings)
shellEmulator: true
