import * as z from "zod";

const planSchema = z.strictObject({
  collaborators: z.int(),
  name: z.string(),
  space: z.int(),
  private_repos: z.int(),
});

const privateUserSchema = z.strictObject({
  login: z.string(),
  id: z.int(),
  user_view_type: z.string().optional(),
  node_id: z.string(),
  avatar_url: z.url(),
  gravatar_id: z.string().nullable(),
  url: z.url(),
  html_url: z.url(),
  followers_url: z.url(),
  following_url: z.string(),
  gists_url: z.string(),
  starred_url: z.string(),
  subscriptions_url: z.url(),
  organizations_url: z.url(),
  repos_url: z.url(),
  events_url: z.string(),
  received_events_url: z.url(),
  type: z.string(),
  site_admin: z.boolean(),
  name: z.string().nullable(),
  company: z.string().nullable(),
  blog: z.string().nullable(),
  location: z.string().nullable(),
  email: z.email().nullable(),
  notification_email: z.email().nullish(),
  hireable: z.boolean().nullable(),
  bio: z.string().nullable(),
  twitter_username: z.string().nullish(),
  public_repos: z.int(),
  public_gists: z.int(),
  followers: z.int(),
  following: z.int(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  private_gists: z.int(),
  total_private_repos: z.int(),
  owned_private_repos: z.int(),
  disk_usage: z.int(),
  collaborators: z.int(),
  two_factor_authentication: z.boolean(),
  plan: planSchema.optional(),
  business_plus: z.boolean().optional(),
  ldap_dn: z.string().optional(),
});

const publicUserSchema = z.strictObject({
  login: z.string(),
  id: z.int(),
  user_view_type: z.string().optional(),
  node_id: z.string(),
  avatar_url: z.url(),
  gravatar_id: z.string().nullable(),
  url: z.url(),
  html_url: z.url(),
  followers_url: z.url(),
  following_url: z.string(),
  gists_url: z.string(),
  starred_url: z.string(),
  subscriptions_url: z.url(),
  organizations_url: z.url(),
  repos_url: z.url(),
  events_url: z.string(),
  received_events_url: z.url(),
  type: z.string(),
  site_admin: z.boolean(),
  name: z.string().nullable(),
  company: z.string().nullable(),
  blog: z.string().nullable(),
  location: z.string().nullable(),
  email: z.email().nullable(),
  notification_email: z.email().nullish(),
  hireable: z.boolean().nullable(),
  bio: z.string().nullable(),
  twitter_username: z.string().nullish(),
  public_repos: z.int(),
  public_gists: z.int(),
  followers: z.int(),
  following: z.int(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  plan: planSchema.optional(),
  private_gists: z.int().optional(),
  total_private_repos: z.int().optional(),
  owned_private_repos: z.int().optional(),
  disk_usage: z.int().optional(),
  collaborators: z.int().optional(),
});

const githubUserSchema = z.union([privateUserSchema, publicUserSchema]);
type GithubUser = z.infer<typeof githubUserSchema>;

export { githubUserSchema, type GithubUser };
