name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck code with TypeScript
        run: pnpm run typecheck

      - name: Lint code with ESLint
        run: pnpm run lint

      - name: Check code formatting with Prettier
        run: pnpm run format:check

      - name: Build
        run: pnpm run build
